[[redirects]]
  from = "/"
  to = "/index-us"
  status = 301
  force = true
  conditions = {Country = ["us"]}

[[redirects]]
  from = "/"
  to = "/index-de"
  status = 301
  force = true
  conditions = {Country = ["de"]}

[[redirects]]
  from = "/"
  to = "/index-uk"
  status = 301
  force = true
  conditions = {Country = ["gb"]}

[[redirects]]
  from = "/"
  to = "/index-fr"
  status = 301
  force = true
  conditions = {Country = ["fr"]}

[[redirects]]
  from = "/"
  to = "/index-it"
  status = 301
  force = true
  conditions = {Country = ["it"]}


[[redirects]]
  from = "/"
  to = "/index-ca"
  status = 301
  force = true
  conditions = {Country = ["ca"]}


[[redirects]]
  from = "/"
  to = "/index-mx"
  status = 301
  force = true
  conditions = {Country = ["mx"]}


[[redirects]]
  from = "/"
  to = "/index-in"
  status = 301
  force = true
  conditions = {Country = ["in"]}

[[redirects]]
  from = "/bodybuilding"
  to = "https://bodybuilding.com"
  status = 200
  force = true
  